### ISSUE TITLE
Sphere{T} = UnitSphere{3,T} is a confusing definition

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaApproximation/Domains.jl#28]
It's not clear why `UnitSphere` refers to an N-sphere while `Sphere` is a 3-sphere. I'd expect a `Sphere` to also have a radius and centre (down the line). So maybe `UnitSphere` -> `UnitHyperSphere` while `Sphere` -> `UnitSphere`.

**Comment by daanhb** [comment]
Yes, `HyperSphere` seems more correct terminology, good point.
There could be a `Sphere` with radius and centre at some point. For the time being, many domains simply have a "basic" type that contains no data, like `UnitSphere` and `ChebyshevInterval`. They come with zero memory overhead and a simple, clean and efficient implementation that does not implicitly favour one affine map over another one. But I agree one would also expect a more fully featured sphere in a package like this.

I digress, but that is something I had in mind with the `DerivedDomain` type, which I think is currently never used and isn't even fully implemented (it should perhaps be removed). The idea is that a domain that derives from `DerivedDomain` has its own type, yet it simply contains some other domain. A sphere could be a `DerivedDomain`, that contains a mapped domain consisting of a `UnitSphere` and an affine map. That's perhaps more complicated than it should be for this use case, but it is a generic way of making domains with more functionality and a richer interface (using dispatch on the new type), while reusing existing (efficient) implementation.

**Comment by dlfivefifty** [comment]
Note that affine translations and domains with parameters are slightly different in IEEE, take the ball defined by: `x^2 + y^2 ≤ r^2` vs the affine version `(x/r)^2 + (y/r)^2 ≤ 1`:
```julia
julia> x,y
(2.1213203608786055, 2.1213203262406797)

julia> x^2 + y^2 ≤ 9
true

julia> (x/3)^2 + (y/3)^2 ≤ 1
false
```
So I think both versions should exist without viewing it as too redundant.

**Comment by MikaelSlevinsky** [comment]
1. Are we going to distinguish between an n-ball and an (n-1)-sphere?

2. Also, is the current "3-sphere" is embedded in R<sup>3</sup> or R<sup>4</sup>? I don't know the design well enough to distinguish whether or not the super type is supposed to be the ambient domain or something that the instance looks like locally. This is rather picky, but there may be ways around this like overriding `supertype`

```julia
julia> struct MyType{N, T}
           center::T
           radius::T
       end

julia> abstract type MyAbstractType{N, T} end

julia> Base.supertype(::MyType{N, T}) where {N, T} = MyAbstractType{N + 1, T}

julia> sph = MyType{2, Float64}(0.0, 1.0)
MyType{2,Float64}(0.0, 1.0)

julia> supertype(sph)
MyAbstractType{3,Float64}
```

**Comment by MikaelSlevinsky** [comment]
What about spheres and balls with different, possibly user-defined, norms? I think generic balls are then closed convex domains, so not sure how much would be gained from this. Perhaps a guarantee that a hyperspherical harmonic expansion is 1-to-1.
