### ISSUE TITLE
Publish to METADATA

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaApproximation/Domains.jl#4]
Before this happens, there should be a discussion with https://github.com/zenna/AbstractDomains.jl about unifying, to avoid multiple packages that do the same thing.

**Comment by daanhb** [comment]
It's fine as it is. Thanks!

**Comment by MikaelSlevinsky** [comment]
I learned recently that following semver usually means starting at v0.1. https://semver.org

**Comment by dlfivefifty** [comment]
The Julia convention is to use 0.0.x to mean experimental (according to Stefan on Discourse the other day)
